// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfqxkNyvDPFfW9GOIQYQF184j612KgVfA',
    appId: '1:478768893149:web:8979ed49e71d319c655f34',
    messagingSenderId: '478768893149',
    projectId: 'bus-system-36efb',
    authDomain: 'bus-system-36efb.firebaseapp.com',
    storageBucket: 'bus-system-36efb.appspot.com',
    measurementId: 'G-9WMFEJK3NF',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwJl1L0GCihWjDwdjwdTIu1sugiNfA1KM',
    appId: '1:478768893149:ios:4a36409394071386655f34',
    messagingSenderId: '478768893149',
    projectId: 'bus-system-36efb',
    storageBucket: 'bus-system-36efb.appspot.com',
    iosBundleId: 'com.example.busSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfqxkNyvDPFfW9GOIQYQF184j612KgVfA',
    appId: '1:478768893149:web:751b5dfed72c9142655f34',
    messagingSenderId: '478768893149',
    projectId: 'bus-system-36efb',
    authDomain: 'bus-system-36efb.firebaseapp.com',
    storageBucket: 'bus-system-36efb.appspot.com',
    measurementId: 'G-7G2EKXM9KW',
  );
}
